from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QComboBox, QLabel
import keyboard


class Dia_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 410)
        Form.setMinimumSize(QtCore.QSize(500, 410))
        Form.setMaximumSize(QtCore.QSize(500, 410))
        Form.setStyleSheet('background-color: rgb(255, 254, 228);')
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 570, 410))
        self.stackedWidget.setObjectName("stackedWidget")

        self.dialog_window = QtWidgets.QWidget()  # диалоговое окно
        self.dialog_window.setObjectName("dialog_window")
        pixset = QtGui.QPixmap(r'settings.png')
        pixset = pixset.scaled(51, 41)
        iconset = QtGui.QIcon(pixset)
        self.settings_button = QtWidgets.QPushButton(self.dialog_window)
        self.settings_button.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.settings_button.setText("")
        self.settings_button.setObjectName("settings_button")
        self.settings_button.setCheckable(True)
        self.settings_button.setIcon(iconset)
        self.settings_button.setIconSize(pixset.rect().size())
        self.settings_button.setFixedSize(pixset.rect().size())
        self.settings_button.setFlat(True)
        self.settings_button.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.settings_button.setStyleSheet('background-color: rgba(255, 255, 255, 0);')
        pixsend = QtGui.QPixmap(r'send.png')
        pixsend = pixsend.scaled(51, 41)
        iconsend = QtGui.QIcon(pixsend)
        self.send = QtWidgets.QPushButton(self.dialog_window)
        self.send.setGeometry(QtCore.QRect(430, 349, 41, 41))
        self.send.setText("")
        self.send.setObjectName("send")
        self.send.setIcon(iconsend)
        self.send.setIconSize(pixsend.rect().size())
        self.send.setFixedSize(pixsend.rect().size())
        self.send.setFlat(True)
        self.send.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.send.setStyleSheet('background-color: rgba(255, 255, 255, 0);')
        pixmicro = QtGui.QPixmap(r'micro.png')
        pixmicro = pixmicro.scaled(41, 51)
        iconmicro = QtGui.QIcon(pixmicro)
        self.micro = QtWidgets.QPushButton(self.dialog_window)
        self.micro.setGeometry(QtCore.QRect(15, 340, 41, 51))
        self.micro.setText("")
        self.micro.setObjectName("micro")
        self.micro.setIcon(iconmicro)
        self.micro.setIconSize(pixmicro.rect().size())
        self.micro.setFixedSize(pixmicro.rect().size())
        self.micro.setFlat(True)
        self.micro.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.micro.setStyleSheet('background-color: rgba(255, 255, 255, 0);')
        self.lineEdit = QtWidgets.QLineEdit(self.dialog_window)
        self.lineEdit.setGeometry(QtCore.QRect(100, 345, 301, 43))
        self.lineEdit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
                                    "border: 1px solid black;\n"
                                    "border-radius: 10px;\n"
                                    "\n""")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Введите текст")
        self.dialog = QtWidgets.QTextBrowser(self.dialog_window)
        self.dialog.setGeometry(QtCore.QRect(70, 20, 400, 311))
        self.dialog.setObjectName("dialog")
        self.stackedWidget.addWidget(self.dialog_window)
        self.dialog.setStyleSheet('background-color: rgb(172, 200, 242);')

        self.settings_window = QtWidgets.QWidget()  # окно настоек
        self.auto_1 = QtWidgets.QCheckBox(self.settings_window)
        self.auto_1.setGeometry(QtCore.QRect(10, 70, 261, 31))
        self.auto_1.setObjectName("auto_1")
        self.settings_button2 = QtWidgets.QPushButton(self.settings_window)
        self.settings_button2.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.settings_button2.setText("")
        self.settings_button2.setObjectName("settings_button2")
        self.settings_button2.setCheckable(True)
        self.settings_button2.setIcon(iconset)
        self.settings_button2.setIconSize(pixset.rect().size())
        self.settings_button2.setFixedSize(pixset.rect().size())
        self.settings_button2.setFlat(True)
        self.settings_button2.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.settings_button2.setStyleSheet('background-color: rgba(255, 255, 255, 0);')
        self.checkBox_2 = QtWidgets.QCheckBox(self.settings_window)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 100, 261, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.settings_window)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 130, 261, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.settings_window)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 160, 261, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.settings_window)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 190, 281, 21))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.settings_window)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 220, 271, 21))
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton = QtWidgets.QPushButton(self.settings_window)
        self.pushButton.setGeometry(QtCore.QRect(340, 350, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.Accept = QtWidgets.QPushButton(self.settings_window)
        self.Accept.setGeometry(QtCore.QRect(10, 350, 111, 51))
        self.Accept.setObjectName("Accept")
        self.textBrowser = QtWidgets.QTextBrowser(self.settings_window)
        self.textBrowser.setGeometry(QtCore.QRect(200, 61, 280, 200))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet('background-color: rgb(172, 200, 242);')
        self.command_line = QtWidgets.QLineEdit(self.settings_window)
        self.command_line.setGeometry(QtCore.QRect(200, 250, 280, 25))
        self.command_line.setObjectName("lineEdit1")
        self.command_line.setPlaceholderText("Название команды")
        self.url_line = QtWidgets.QLineEdit(self.settings_window)
        self.url_line.setGeometry(QtCore.QRect(200, 300, 280, 25))
        self.url_line.setObjectName("lineEdit2")
        self.url_line.setPlaceholderText("Введите ссылку")
        self.settings_window.setObjectName("settings_window")
        self.combo = QtWidgets.QComboBox(self.settings_window)
        self.combo.setGeometry(QtCore.QRect(200, 275, 280, 25))
        self.combo.setObjectName("combo")
        for day in range(1, 31):
            self.combo.addItem('%d' % day)
        self.stackedWidget.addWidget(self.settings_window)
        self.stackedWidget.addWidget(self.settings_window)
        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)

        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("Ведьмачел")
        Form.setWindowIcon(QtGui.QIcon('ved.png'))
        self.auto_1.setText(_translate("Form", "Запускать автоматически"))
        self.checkBox_2.setText(_translate("Form", "CheckBox"))
        self.checkBox_3.setText(_translate("Form", "CheckBox"))
        self.checkBox_4.setText(_translate("Form", "CheckBox"))
        self.checkBox_5.setText(_translate("Form", "CheckBox"))
        self.checkBox_6.setText(_translate("Form", "CheckBox"))
        self.pushButton.setText(_translate("Form", "Добавить команду"))
        self.Accept.setText(_translate("Form", "Подтвердить"))
